[package]
name = "openclaw"
version = "0.1.0"
description = "OpenClaw - Bonding curve token launchpad on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "openclaw"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

[dev-dependencies]
solana-program-test = "1.18"
solana-sdk = "1.18"
tokio = "1.36"
